### ISSUE TITLE
Xmas tree live coding app

### ISSUE THREAD

**Issue by sirxemic** [standupmaths/xmastree2021#18]
Was not sure where to share this. Since I've seen people share their own utilities here in the issues & pull requests, figured I could do the same.

Here is a little app where you can write JS code and see the effect immediately in the browser. It also supports playing CSV files. 

Enjoy!

https://sirxemic.github.io/xmastree-app/

**Comment by d-albrecht** [comment]
I guess you should add this as a pull request for the further works section because here it might be forgotten.

Do you assume the column headers to be upper case? My csv file again doesn't play at all. And I had this exact same issue with another simulator. [test file](https://raw.githubusercontent.com/d-albrecht/XMas-Tree-Explosions/main/v1/explosions.csv)

**Comment by sirxemic** [comment]
I consider files that start with `FRAME_ID` to be valid, since the example files at https://github.com/GSD6338/XmasTree/tree/main/misc start with that. I guess in practice the first line will always be skipped regardless of the contents, so I'll make my importer do the same.

I'll also create the PR.

**Comment by oliverdunk** [comment]
Very cool! Going to close this in favor of https://github.com/standupmaths/xmastree2021/pull/19 just to keep things organised.
