### ISSUE TITLE
Max file size per example

### ISSUE THREAD

**Issue by santiagodg** [standupmaths/xmastree2021#47]
There are some already submitted examples that go up to almost 20 MB in size. Last year, we had animation scripts which are light, but this year's CSV are much heavier. It may be hard to play various animations if the hardware's storage is filled with few animations that are too large.

Should animators be concerned with a file size limit? Should we set a max file size?

**Comment by d-albrecht** [comment]
We had one submission already (the flags) that was quite large, but the problem wasn't overall storage size but the size limit for this individual file. After it was split in five (with essentially the same if not more overall size), the submission was merged. My conclusion: If possible, keep the sizes for individual files low (and split the animation if this makes sense), but storage seems to not the an issue here. In case that's necessary, Matt might just move the files from/to the RPi in between, I guess.

But GitHub (and mail attachments) have a max file size, so if you consider those ways of submission, then rather look at these technical size limits. ;)

I already noticed myself that pre-rendered animations are really large. And that I should have spent the effort to submit last year despite the different format because I would have been much more flexible. You can't even alter the color scheme of your animation without creating a whole new file. And compression isn't a thing yet, either.

**Comment by oliverdunk** [comment]
Within reason I wouldn't be concerned - as a rough benchmark below 50MB is probably sensible? I'm not saying we won't merge things above that but if every submission was bigger than that, we might start to get concerned.

As @d-albrecht says, there are some technical limitations in GitHub, but those are fairly large. Beyond that, it's just a case of:

- Avoiding making it too infeasible to download the entire repo
- Avoiding files that are impossible to load in to RAM

Ideally the limit would be much smaller, but since we can't change the CSV format now, I'd rather deal with some big files than start rejecting genuine submissions.
